### ISSUE TITLE
Implement `stop_on_end` keyword argument for `TranscodingStream(::Noop, ::IO)` constructor

### ISSUE THREAD

**Issue by reallyasi9** [JuliaIO/TranscodingStreams.jl#128]
The `Noop` codec specializes the method `TranscodingStream(::Noop, ::IO)` at https://github.com/JuliaIO/TranscodingStreams.jl/blob/79738b511afaee103957eaf03e6e92fbef8adfe3/src/noop.jl#L31-L33
but it does not include the `stop_on_end` keyword argument in its list of possible keyword arguments as defined at https://github.com/JuliaIO/TranscodingStreams.jl/blob/79738b511afaee103957eaf03e6e92fbef8adfe3/src/stream.jl#L113-L116
This means if a user wants to make a `TranscodingStream`, the user has to know the type of the codec before knowing what arguments to pass to the constructor.

For example, only one of the branches in this example works:
```julia
# define file_name somewhere above
input = NoopStream(open(file_name, "r"))
if last(splitext(file_name)) == ".gz"
    codec = GzipDecompressor()
else
    codec = Noop()
end

stream = TranscodingStream(codec, input; stop_on_error=true) # fails if codec isa Noop
```

**Comment by nhz2** [comment]
Fixed in #178
