### ISSUE TITLE
Ideas to improve speed

### ISSUE THREAD

**Issue by jdiaz97** [JuliaIO/TranscodingStreams.jl#150]
Hello!

Referencing this: https://github.com/JuliaIO/BufferedStreams.jl/issues/62#issuecomment-1156343485

Is there any way to get better performance using TranscodingStreams? are some changes necessary in the codebase? I'm willing to help.

**Comment by jakobnissen** [comment]
@jdiaz97 

Sorry for only seeing your issue this late.
The overall problem with this package it that it has no real maintainer. There are a bunch of people with commit rights who sometimes makes PRs, but no-one has taken ownership over it. With this, I mean that no-one has spent the time to know the code in this package, why it is like it is, it's design tradeoffs, etc.
So - a bunch of people, like me, are able to make bugfixes here and there, but without spending the weeks necessary to really dive into the package, none of us have the overview to understand how to rewrite this package for maximal performance.

It'd be amazing if you are willing to take this package under your wings, but I understand this is a big ask.
