### ISSUE TITLE
The buffer growth behaviour of TranscodingStreams

### ISSUE THREAD

**Issue by TransGirlCodes** [JuliaIO/TranscodingStreams.jl#48]
Hey @bicycle1885, I was reviewing the new Stream module of Automa and was getting to grips with it and ended up with some questions and observations.

### 1. BufferedStreams buffer growth is sometimes undesirable

I realised with the system of anchoring we used with BufferedStreams & Automa, the buffers in the BufferedStream double in size when:
* The Automa machine reached the end of a buffer and...
* When was not finished reading a record and...
* No space could be freed inside the buffer, as it was all preserved by the anchor mechanism.

So if you're reading in say a FASTA file, if you have some very large sequences, the doubling in size of the buffers will happen frequently enough to cause large memory allocations which will be a performance problem, perhaps even preventing some files from being read altogether. I anticipate this being an issue with genome graphs and reference sequences, where you will have a whole range of node sizes from very small sequences, to really very large contigs.

### 2. I checked if TranscodingStreams would grow in the same way

I think the answer to that is yes. Because of these two lines:
* https://github.com/BioJulia/Automa.jl/blob/7a0791c562356a846cc44527fcc35f65a2a78dc0/src/Stream.jl#L114
* https://github.com/BioJulia/Automa.jl/blob/7a0791c562356a846cc44527fcc35f65a2a78dc0/src/Stream.jl#L120

* The first line calls eof(stream), the second line calls the `Base.skip` method, which also eventually calls `eof(stream)`.
* `eof(stream)` calls `fillbuffer` if there's no more buffered data that is unconsumed.
* `fillbuffer` then does some stuff - critically it calls `makemargin!`, which shifts preserved data, to ensure there is space in the buffer, and resizing the buffer it if there is not enough space.

So it seems to me that this will still be an issue? The buffers will grow in size? 

### 3. Can anything be done to improve this?

I was wondering if we could do something so as to keep the buffer growth as limited as possible when TranscodingStreams and used with Automa.Stream, and maybe even a fixed size?

I suspect fixed size buffers is not possible (although it could be in BufferedStreams), as TranscodingStreams (unlike BufferedStreams) also have to deal with any kind of codec, and sometimes buffer1 may need to grow a bit when it recieves some data from the [buffer1 <---- codec <----- buffer2] process.

But perhaps there is something we can do on the Automa side to reduce the amount of marked data kept in the buffer?
Perhaps in the Automa.Stream code, we can check the amount of marked data present in the buffer and the amount of space left in the buffer, and if a buffer resize would occur on the next `eof` or `Base.skip` call, then take the data marked so far and take make a partial write of the field to the record, and empty the buffer.

Or, perhaps we could give the Reader types their own fixed size buffer,
Which gets filled from a TranscodingStream in one go. Then, Automa gets to the end of
that buffer, then any marked data in the buffer get's written to the output record object and then the entire buffer is refilled.

I'd like to get your opinion on this, let me know what you think. If it's something worth persuing I'm happy to do so.

**Comment by bicycle1885** [comment]
I didn't check it carefully, but I designed it so that buffers in a transcoding stream do not grow so much (e.g. <=16 KiB or so) if you copy buffered data into a result record, say, line by line. A chunk of buffered data may be relocated when calling `makemargin!` even when there are marked data, but I found it was difficult to keep track of the position of marked data if it may be relocated while parsing.  That's why I introduced some utility macros to get the absolute/relative position of a data chunk:
https://github.com/BioJulia/Automa.jl/blob/7a0791c562356a846cc44527fcc35f65a2a78dc0/src/Stream.jl#L33-L49. These macros will make it easier to relocate a chunk of buffered data while parsing. Anyway, I think the problem of doubling buffer size is no longer a problem if we carefully write parsers.
