### ISSUE TITLE
Method for closing the transcoding stream without closing the underlying stream

### ISSUE THREAD

**Issue by oxinabox** [JuliaIO/TranscodingStreams.jl#85]
I am using a transcoding stream to write compressed data to a `IOBuffer`,
which I then want to call `take!` on to get an array.

I need to close the transcodings stream to get all the end of compressed data stuff written to the underlying stream,
but I need to leave the underlying stream open so that I can call `take!` on it.

Right now my plan is to just call a  `changemode!(stream, :close)` directly.

https://github.com/bicycle1885/TranscodingStreams.jl/blob/9393f359d321e8a87293060694cfd2a4956728f4/src/stream.jl#L171-L180

I feel like an option could be added as a kwarg to `close`, like:
`code(stream::TranscodingStream; close_backing_stream = true)`

**Comment by oxinabox** [comment]
hmm, I think I have misunderstood how thing hangs together as that didn't do what I wanted

**Comment by nhz2** [comment]
If the `stop_on_end = true` keyword argument is set when constructing the transcoding stream. the underlying stream now isn't closed when the transcoding stream is closed.
